- hosts: all
  become: true
  pre_tasks:
  
  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Centos"
    
  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
- hosts: Ubuntu_elk
  become: true
  roles:
    - Ubuntu_elk

- hosts: CentOS_elk
  become: true
  roles:
    - CentOS_elk
